### ISSUE TITLE
Support ClickHouse as backend storage instead of ElasticSearch

### ISSUE THREAD

**Issue by Slach** [mehrdadrad/tcpdog#1]
Hello @mehrdadrad 
great tool ;)

could you look to https://clickhouse.tech/docs/en/
and to https://github.com/Altinity/clickhouse-grafana/ ?

and consider feature support ClickHouse as backend storage instead of ElasticSearch?
ClickHouse it's a blazing fast columnar database that can be much effective storage for your use-case

**Comment by mehrdadrad** [comment]
Hello @Slach,  Great idea! actually I was thinking about clickhouse but I wanted to add it later. I had great experience with clickhouse 4-5 years ago with vFlow: https://github.com/VerizonDigital/vflow/tree/master/consumers/clickhouse

**Comment by Slach** [comment]
;) @mehrdadrad I glad to hear it you already know about ClickHouse ;)
if you will have questions about table data structures and something else related to clickhouse, please ask 

unfortunately. I haven't free time to help you and make PR

**Comment by mehrdadrad** [comment]
The clickhouse package has been added, I'll close this issue and if you get a chance please let me know if you see any issues.
